version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package_1.zip *
      - cd ..
      - zip -g deployment_package_1.zip doordashprocessing.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_1.zip s3://lambda-builds-zip19/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordashprocessing --s3-bucket lambda-builds-zip19 --s3-key deployment_package_1.zip
      - echo "Deployment complete!"