version: 0.2

phases:
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package_1.zip doordashprocessing.py

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_1.zip s3://lambda-builds-zip19/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordashprocessing --s3-bucket lambda-builds-zip19 --s3-key deployment_package_1.zip
      - echo "Deployment complete!"
