version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  build:
    commands:
      - echo "Optimizing dependencies and zipping deployment package..."
      - cd lib
      - find . -name '*.pyc' -delete  # Remove .pyc files to reduce size
      - zip -r9 ../deployment_package_1.zip *   # Compress with maximum compression
      - cd ..
      - zip -g deployment_package_1.zip doordashprocessing.py  # Add main script
      - echo "Current size of deployment package:"
      - unzip -l deployment_package_1.zip | tail -n1 | awk '{print $1}'

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_1.zip s3://lambda-builds-zip19/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordashprocessing --s3-bucket lambda-builds-zip19 --s3-key deployment_package_1.zip
      - echo "Deployment complete!"
